---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seerr

resources:
- ../../cluster/base/namespaces/seerr
- base

patches:
  - path: overlays/statefulset.yaml

helmCharts:
  - name: seerr-chart
    valuesFile: overlays/values.yaml
    includeCRDs: true
    version: 3.0.2
    repo: oci://ghcr.io/seerr-team/seerr
    namespace: seerr
    releaseName: seerr-chart

