---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate

resources:
- ../../cluster/base/namespaces/renovate
- base

helmCharts:
  - name: renovate-operator
    valuesFile: overlays/values.yaml
    includeCRDs: true
    version: 2.8.3
    repo:  oci://ghcr.io/mogenius/helm-charts
    namespace: renovate
    releaseName: renovate-operator


