---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate

resources:
- ../../cluster/base/namespaces/renovate
- base

helmCharts:
  - name: renovate
    valuesFile: overlays/values.yaml
    includeCRDs: true
    version: 46.14.1
    repo: oci://ghcr.io/renovatebot/charts
    namespace: renovate
    releaseName: renovate


