---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - base/

helmCharts:
  - name: headlamp
    includeCRDs: true
    version: 0.40.0
    valuesFile: overlays/values.yaml
    repo: https://kubernetes-sigs.github.io/headlamp/
    namespace: kube-system
    releaseName: headlamp

