---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myspeed

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`myspeed.internal`)
      kind: Rule
      services:
        - name: myspeed
          port: 5216

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: speedtest

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`speedtest.internal`)
      kind: Rule
      services:
        - name: speedtest
          port: 3000


