---
apiVersion: v1
kind: Service
metadata:
  name: myspeed
spec:
  ports:
    - port: 5216
  selector:
    app: myspeed

---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
spec:
  ports:
    - port: 3000
  selector:
    app: speedtest

