---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
- base
- ../../cluster/base/namespaces/cert-manager

helmCharts:
  - name:  cert-manager
    includeCRDs: true
    repo: https://charts.jetstack.io 
    version: v1.19.4
    valuesFile: overlays/values.yaml
    namespace: cert-manager
    releaseName: cert-manager

