---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd
  - audiobookshelf
  - cert-manager
  - external-secrets-operator
  - intel-device-plugins-gpu
  - headlamp
  - homepage
  - jellyfin
  - node-feature-discovery
  - uptime-kuma
  - speed-test
  - seerr
  - reloader
  - renovate
