---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-feature-discovery

resources:
- ../../cluster/base/namespaces/node-feature-discovery/
- https://raw.githubusercontent.com/intel/intel-device-plugins-for-kubernetes/main/deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml

helmCharts:
  - name: node-feature-discovery
    includeCRDs: true
    version: 0.18.3
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    namespace: node-feature-discovery
    releaseName: node-feature-discovery

