apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-config
spec:
  capacity:
    storage: 150Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/jellyfin/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: platform
          operator: In
          values:
          - n100
