---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

resources:
- ../../cluster/base/namespaces/external-secrets
- base

helmCharts:
  - name: external-secrets
    valuesFile: overlays/values.yaml
    includeCRDs: true
    version: 2.0.1
    repo: https://charts.external-secrets.io
    namespace: external-secrets
    releaseName: external-secrets

