---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`seerr.internal`)
      kind: Rule
      services:
        - name: seerr-chart
          port: 80


