---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- externalSecretGithubKey.yaml
- externalSecretRenovateGithub.yaml
- generatorGithubApp.yaml
- ingress.yaml
- renovateJob.yaml
