apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader

resources:
- ../../cluster/base/namespaces/external-secrets
- https://github.com/stakater/Reloader/deployments/kubernetes

