---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../cluster/base/namespaces/argocd
- base
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml

patches:
- path: overlays/argocd-cmd-params-cm.yaml
- path: overlays/argocd-cm.yaml
- path: overlays/argocd-rbac-cm.yaml

images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argo-cd/argocd
  newTag: 3.4.0-4409ec0a
